# Joint state controller
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# Joint trajectory controller (position)
panda_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  gains:
    panda_joint1: {p: 100.0, d: 10.0, i: 0.0}
    panda_joint2: {p: 100.0, d: 10.0, i: 0.0}
    panda_joint3: {p: 100.0, d: 10.0, i: 0.0}
    panda_joint4: {p: 100.0, d: 10.0, i: 0.0}
    panda_joint5: {p: 100.0, d: 10.0, i: 0.0}
    panda_joint6: {p: 100.0, d: 10.0, i: 0.0}
    panda_joint7: {p: 100.0, d: 10.0, i: 0.0}
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.01
  state_publish_rate: 50
  action_monitor_rate: 20